version: '3.0'
services:
  opendj:
    image: openidentityplatform/opendj:4.5.9
    container_name: opendj
    ports:
      - 11389:1389
      - 4445:4444
    environment:
      - ROOT_USER_DN=cn=Directory Manager
      - ROOT_PASSWORD=secret
      - BASE_DN=dc=inflinx,dc=com
    restart: always
    
  apache-directory-studio:
    container_name: apache-directory-studio
    image: clickbg/apache-directory-studio:latest 
    ports:
      - 5901:5901
